services:
  # API Server Database
  api-db:
    image: postgres:16
    container_name: api-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_db
    ports:
      - '5433:5432'
    volumes:
      - api-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  # MongoDB for Event Store
  eventstore-mongodb:
    image: mongo:7
    container_name: eventstore-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: eventstore
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: eventstore
    ports:
      - '27017:27017'
    volumes:
      - eventstore-mongodb-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.adminCommand("ping")']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  api-db-data:
  eventstore-mongodb-data:
