services:
  # API Server Database
  api-db:
    image: postgres:16
    container_name: api-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_db
    ports:
      - '5433:5432'
    volumes:
      - api-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  # Auth Server Database
  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - '5434:5432'
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  api-db-data:
  auth-db-data:
